### ISSUE TITLE
Реализация бек-энда для загрузки фотографий

### ISSUE THREAD

**Issue by Aleksei-Pankratev-EPAM** [Aleksei-Pankratev-EPAM/CherryPeakBidding#19]
Linked to #18 

Необходимо реализовать API для загрузки фото по создаваемому лоту. Особенность: фотографии загружаются для еще не существующего лота и привязываются к нему в момент создания. Возможно, имеет смысл заранее генерировать GUID на клиентской стороне.

**Comment by Sofia-Vaks-EPAM** [comment]
- Каждая фотография загружается отдельный вызовом API /api/photos и сохраняется сразу в хранилище

- Для хранения будем использовать Amazon S3

- Приоритет фотографии будет определяться по дате загрузки фото
